sudo: required

language: python

python:
  - 3.5

services:
  - docker

before_install:
  - docker build . -f ./docker/Dockerfile -t milesg/gap-statistic:1.0

install:
  - pip install coveralls

script:
  docker run --rm -v `pwd`:`pwd` -w `pwd` milesg/gap-statistic:1.0 coverage run --source=gap_statistic setup.py test

after_success:
  - coverage combine --append
  - coveralls