version: 0.2.{build}
image:
  - Visual Studio 2017
environment:
  matrix:
    - PYTHON: "C:/Python35-x64"
      TARGET: x86_64-pc-windows-msvc

    - PYTHON: "C:/Python36-x64"
      TARGET: x86_64-pc-windows-msvc

    - PYTHON: "C:/Python35"
      TARGET: i686-pc-windows-msvc

    - PYTHON: "C:/Python36"
      TARGET: i686-pc-windows-msvc

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python --version"
  - ps: Start-FileDownload "https://static.rust-lang.org/dist/rust-nightly-${env:TARGET}.msi"
  - start /wait msiexec /i rust-nightly-%TARGET%.msi INSTALLDIR="%CD%\rust-nightly-%TARGET%" /quiet /qn /norestart
  - set PATH=%PATH%;%CD%/rust-nightly-%TARGET%/bin
  - rustc -V
  - cargo -V
  - set RUST_BACKTRACE=1
  - pip install -r requirements.txt
  - pip install --upgrade setuptools-rust pytest pytest-benchmark wheel

build_script:
  - python setup.py build_ext
  - python -m pip -v wheel . -w .\\wheelhouse
  - dir wheelhouse

test_script:
  - cargo test
  - python -m pip -v install gap-stat --no-index -f wheelhouse
  - python -m pip install scikit-learn scipy numpy pandas joblib
  - python -m pytest tests

artifacts:
  - path: wheelhouse\gap*.whl